version: '3.8'

services:
  api:
    build: .
    ports:
      - "8005:8000"
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql://allbounds:allbounds@db:5432/allbounds
      - MEILISEARCH_URL=http://meilisearch:7700
      - MEILISEARCH_MASTER_KEY=masterKey
      - R2_ENDPOINT=
      - R2_ACCESS_KEY=
      - R2_SECRET_KEY=
      - R2_BUCKET_NAME=allbounds
      - JWT_SECRET_KEY=dev_secret_key_change_in_production
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=43200
      - JWT_REFRESH_TOKEN_EXPIRE_DAYS=14
    depends_on:
      - db
      - meilisearch
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  db:
    image: postgres:15-alpine
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=allbounds
      - POSTGRES_PASSWORD=allbounds
      - POSTGRES_DB=allbounds
    volumes:
      - postgres_data:/var/lib/postgresql/data

  meilisearch:
    image: getmeili/meilisearch:v1.3
    ports:
      - "7705:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
    volumes:
      - meilisearch_data:/meili_data

volumes:
  postgres_data:
  meilisearch_data:
